version: "3.9"

services:
  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/backend:latest
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${{ secrets.DATABASE_URL }}
      - SESSION_SECRET_KEY=${{ secrets.SESSION_SECRET_KEY }}
    networks:
      - app-network
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresD
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge
