version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: prod
      dockerfile: frontend.dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb?schema=public
    depends_on:
      - db
    volumes:
      - ./backend/:/app
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresD
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
